### ISSUE TITLE
docker-compose 사용하기

### ISSUE THREAD

**Issue by kakasoo** [rimo030/Repo-Server#8]
프로젝트 폴더의 root에 아래 코드를 복사해서 `docker-compose.yml` 파일을 만드세요.
이후에 root 폴더에서 docker compose up -d를 입력하면 MySQL이 설치됩니다.
단, 이미 MySQL을 사용 중이라면 제가 말한 걸 하기 전에 먼저 말씀해주세요.

```yml
version: "3"
services:
  # 서비스 명
  mysql:
    # 사용할 이미지
    image: mysql:8.0

    # 컨테이너 실행 시 재시작
    restart: always

    # 컨테이너명 설정
    container_name: RepoServerDB

    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "3306:3306"

    # 환경 변수 설정
    environment:
      MYSQL_ROOT_PASSWORD: password

    # 명령어 설정
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
```
